### ISSUE TITLE
unable to set model

### ISSUE THREAD

**Issue by rmontesinos** [TAGonSoft/groq-dart#11]
I'm unable to set the model and keeps using the default value: llama270b4096
then I got an error telling that model is not available.
groq = Groq('MY_API_KEY',model: GroqModel.llama370b8192);
even defining the model it keeps using the default value.

**Comment by stefantagonsoft** [comment]
Hello,

Thank you for reporting the issue! We've identified and fixed the problem where the model was not being set correctly and defaulted to `llama270b4096`. The update is included in version 1.0.0. 

Please update to the latest version, and let us know if you encounter any further issues.

Best regards,  
The Development Team
