### ISSUE TITLE
Bug ,need help

### ISSUE THREAD

**Issue by chenjun1127** [TAGonSoft/groq-dart#15]
{
  "error": {
    "message": "Unknown request URL: GET /openai/v1/chat/completions. Please check the URL for typos, or see the docs at https://console.groq.com/docs/",
    "type": "invalid_request_error",
    "code": "unknown_url"
  }
}
I've used my key, and the following error appears, what is the reason?

**Comment by stefantagonsoft** [comment]
Hello,

The issue you're encountering has likely been resolved in the latest version of the package. Please update to version 1.0.0, which includes fixes and improvements. 

If the problem persists after updating, let us know, and we’ll assist further.

Best regards,  
The Development Team
